### ISSUE TITLE
assets-common is missing

### ISSUE THREAD

**Issue by axelbsa** [framefield/tooll#1]
Managed to compile Tooll and copy the Operators (default git path is set to git+ssh which my key fails), but i can't find any assets-common folder, which tooll.oi is looking for (at least Deafault.fx). So i hacked a default.fx to together and managed to start the application, unfortunately more is missing.

**Comment by pixtur** [comment]
Sorry to here that. The instructions were still incomplete. I updated the project's readme file. Could you please try to follow the instruction and see, if it works for you?

**Comment by axelbsa** [comment]
Works nice after copying in assets-common

**Comment by pixtur** [comment]
Awesome. Thanks for the update. To open and view all demo-projects you probably want to download the complete [Revision Release](https://github.com/framefield/tooll/releases/tag/v2.4.0-pre).
