### ISSUE TITLE
Question: Minimal start-up configuration?

### ISSUE THREAD

**Issue by Skinnytorus** [framefield/tooll#10]
Hi, @pixtur 
The pre-built version of Tooll2 appears to load up quite a bit of projects at startup. I wonder how to make a "clean" minimal start-up config without losing any of the functionality?
Many thanks in advance.

**Comment by drcynic** [comment]
Remove the Config/Home.mop file, Tooll will create an empty one on start up then

**Comment by Skinnytorus** [comment]
hi, @drcynic 
Thanks for the info, but what if I want to create my own startup setup? What steps should I follow?

**Comment by pixtur** [comment]
Thanks for the feedback: I added some documentation on the [Operators-Wiki-Page](https://github.com/framefield/tooll/wiki/Operators).
