### ISSUE TITLE
logger 

### ISSUE THREAD

**Issue by necaremus** [framefield/tooll#14]
i have a question about the logger:
it took me forever to actually find why the logger didn't write into the file. the `_fileWriter.Flush()` function actually nearly never got called, and `_fileWriter.AutoFlush` wasn't set to `true`.

holy sheet... how long i took to understand / find out that the `_fileWriter.Write("stuff")` did not write at all... x_X

i've now added:

``` C#
        public FileWriter(String filename)
        {
            _fileWriter = new StreamWriter(filename);
+#if DEBUG
+            _fileWriter.AutoFlush = true;
+#endif
        }
```

i think `_fileWriter.AutoFlush = true;` should be used every time - not only in `DEBUG`-mode

> is there a reason for the logger to wait a looooong time until it actually `.Flush()`, that i missed?

**Comment by necaremus** [comment]
i've coded like half a new logger, until i noticed my problem was solved with a one-liner >_>

**Comment by pixtur** [comment]
Hi, please check [my comment in the pull-request](https://github.com/framefield/tooll/pull/13#issuecomment-204130358) . I'm really not sure we should change that line, because it might have severe performance impacts. Did you test, if the makes no visible impact even when writing several Logger.Info("") message per frame?

**Comment by necaremus** [comment]
@pixtur 
i can't rly test it myself too well (my machine isn't powerful enough to handle most of the functions provided by tooll)
but i think the version i uploaded with `#if DEBUG` should be no problem, because it only alters the logger in DEBUG-mode, which you will rarely to never use while working with tooll ;)

i thought something like that could be the case -> that was the reason i only enabled it in DEBUG-mode :)

**Comment by pixtur** [comment]
Okay, that's actually a good point. Convinced.
