### ISSUE TITLE
Missing libs in the pre-built version?

### ISSUE THREAD

**Issue by Skinnytorus** [framefield/tooll#18]
Hey, guys.
I've noticed two libs are missing from the pre-built version:
Mono.Security.dll
ICSharpCode.SharpZipLib.dll
Is that an oversight? Or maybe that was done intentionally?

Thanks in advance for the explanation.

**Comment by pixtur** [comment]
Sorry about this. We fixed this already and a new release is coming up.

**Comment by Skinnytorus** [comment]
Cool. Many thanks for that.
