### ISSUE TITLE
Feature Request: Add hotkeys for Find and Find and Replace

### ISSUE THREAD

**Issue by Skinnytorus** [framefield/tooll#19]
Well... The title speaks for itself :)) Actually, searching for operators is a common task, so having respective hotkeys seems quite natural in terms of usability.
Thank you.

**Comment by necaremus** [comment]
u are not talking about the `tab` function?
if i understand correctly: you wanna press `strg+f` for a pop-up with which you can search your created  stuff?

**Comment by Skinnytorus** [comment]
hi,  @necaremus 
Thanks, I see now. The shortcut was not mentioned neither in the shortcut list nor in the menu. 
Issue closed.

**Comment by pixtur** [comment]
Sorry about that. Maybe you can add it to the wiki...

**Comment by pixtur** [comment]
Hot keys are quiet contextual. The search and replace if operator instances is very(!) rare. I needed it a couple of times over the last couple of years. When editing code, ctrl-F opens a dialog that is not very beautiful but roughly does its job.

Search for operator types to create is such a frequent task, that pressing a control key would be cumbersome.

Btw: you can also double click on the background will open the quick search window.

**Comment by Skinnytorus** [comment]
Done.

> Sorry about that. Maybe you can add it to the wiki...
