### ISSUE TITLE
connection failure attempting to load Operators from git

### ISSUE THREAD

**Issue by necaremus** [framefield/tooll#2]
Framefield.Tooll.ShutDownException was unhandled by user code
HResult=-2146233087
Message=Unable to download operators from: git@github.com:framefield/tooll_operators.git ()

 You may find more details in your log-file.
   Source=Tooll
   Title=Connection Failure
   StackTrace:
        at Framefield.Tooll.CloneRepositoryProgressDialog.<>c__DisplayClass13_0.<CloneReposAsync>b__0() in C:\Users\neeca\Documents\GitHub\tooll\Tooll\Components\Dialogs\CloneRepositoryProgressDialog.xaml.cs:line 66
        at System.Threading.Tasks.Task.Execute()
   InnerException:

---

"You may find more details in your log-file." -> The log-files in ...\tooll\Log\ are empty. :/

**Comment by drcynic** [comment]
Are you working with the latest state? I pushed a fix for this this morning: https://github.com/framefield/tooll/commit/35cf1bcc0a593a601fa433d962494fccfa95b700

**Comment by necaremus** [comment]
like i thought - it was a stupid mistake on my end:

> i made a mistake with [creating a SSH-Key](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) and [**registering it.**](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account)

stupid me assumed, after the file is on my hard-drive, everything else would be automated ~_~
first time working with git and git-hub :3

**Comment by necaremus** [comment]
i would like to handle this exception, in case there will be a 2nd person as stupid as me :D 
Yes/No?

**Comment by pixtur** [comment]
Sure. Sounds great. How do you want to handle the exeception. One solution could be using tooll's ShutDownException-Method... Do you have a message in mind? Maybe we could also add a link to the [github wiki](https://github.com/framefield/tooll/wiki/Requirements-and-Setup) ?

**Comment by necaremus** [comment]
uhm... i'm not too sure about that, yet. wanted to look into it, if i can find additional information in the `try { /*clone from git*/} catch (exception e) {/*handle exception*/}` part of the [CloneRepositoryProgressDialog.xaml.cs](https://github.com/framefield/tooll/blob/master/Tooll/Components/Dialogs/CloneRepositoryProgressDialog.xaml.cs)

``` C#
private async Task CloneReposAsync(OperatorGitRepository repos, IProgress<ProgressState> progress)
        {
            await Task.Run(() =>
                           {
                               try
                               {
                                   Git.CloneRepository()
                                      .SetProgressMonitor(new ProgressMonitor(progress))
                                      .SetURI(repos.RemotePath)
                                      .SetDirectory(new FilePath(repos.LocalPath))
                                      .Call();

                               }
                               catch (Exception)
                               {
                                   var errorText = string.Format("Unable to download operators from: {0}\n\nYou may find more details in your log-file.",
                                                                 repos.RemotePath + " (" + repos.Branch + ")");
                                   throw new ShutDownException(errorText, "Connection Failure");
                               }
                           });
        }
```

gonna need to create an unregistered ssh-key for that again ;D

**Comment by drcynic** [comment]
You can use Exception.Message and Exception.InnerException.Message. At least in the case for the problem of this fix https://github.com/framefield/tooll/commit/35cf1bcc0a593a601fa433d962494fccfa95b700 the message of the inner exception was quite useful as it directly named the assembly that it couldn't load.

**Comment by necaremus** [comment]
mhm... i think i misjudged this.
the exception gets handled way later and visual studios is just "too scared" because the exception gets thrown a long way.

> visual studios is throwing a preemptive `Exception doesn't get handled` error?

but there seems to be something buggy still: the application doesn't shut down correctly :/ 
... i'm not sure about this >_<

**Comment by DannyCork** [comment]
I have a ssh key on github and successfully cloned git@github.com:framefield/tooll.git using ssh auth.

I then built and ran tool.exe but it complains:

![2016-08-18_1616](https://cloud.githubusercontent.com/assets/3512672/17780221/86893ff6-6562-11e6-8159-b2bad4b207e0.png)

`16:36:24.492 (INF): Tooll is starting up at 08/18/2016 16:36:24
16:36:24.497 (INF): Version: T2 - 0.0.2.6.666 (master, 17e1aac)
16:36:26.693 (INF): NSch.JSchException: Auth fail
   at NSch.Session.Connect(Int32 connectTimeout)
   at NGit.Transport.JschConfigSessionFactory.GetSession(URIish uri, CredentialsProvider credentialsProvider, FS fs, Int32 tms)
16:36:26.697 (INF): NGit.Errors.TransportException: git@github.com:framefield/tooll_private_operators.git: Auth fail
   at NGit.Transport.JschConfigSessionFactory.GetSession(URIish uri, CredentialsProvider credentialsProvider, FS fs, Int32 tms)
   at NGit.Transport.SshTransport.GetSession()
   at NGit.Transport.TransportGitSsh.SshFetchConnection..ctor(TransportGitSsh _enclosing)
   at NGit.Transport.TransportGitSsh.OpenFetch()
   at NGit.Transport.FetchProcess.ExecuteImp(ProgressMonitor monitor, FetchResult result)
   at NGit.Transport.FetchProcess.Execute(ProgressMonitor monitor, FetchResult result)
   at NGit.Transport.Transport.Fetch(ProgressMonitor monitor, ICollection`1 toFetch)
   at NGit.Api.FetchCommand.Call()
`
Why is it complaining about the auth when cloning the repo above went fine ?

thanks in advance.
