### ISSUE TITLE
Crashing AMD Display Drivers when choosing "Phong Shading"

### ISSUE THREAD

**Issue by kolnogorov** [framefield/tooll#30]
Tooll crashes every time i run it on two diffentenc PCs (both at my work and home) almost in the same cases. 

It crashes when i choose "Phong Shading". Well, maybe it crashes in some other cases too - I've just tried tooll today for the first time (first at home and then on my work), and haven't time to explore it enough :) But when i choose "Phong Shading" - it crashes.

I have Win10 on both PCs: one with Core i7/12GB RAM/Radeon HD 4500 and the other is AMD Phenom X4/8GB Ram/Radeon HD 5800.

Error message from system says that AMD Display Drivers was crashed and restored. Tooll application doesn't work after that, I must kill the system process and run it again.

Crash log: http://skrju.thesuper.ru/temp/2016_08_30-16_35_29_165.log
Animated GIF Screen Capture: http://skrju.thesuper.ru/temp/tooll-crash.gif

Thank you!

**Comment by pixtur** [comment]
Hi Alex,

tooll.io requires a graphics card that supports DirectX 11.0 or later. As I can see in your animated gif, the console prints that your display adapter only supports feature level 10_1.

Maybe updating the driver can fix this. If not, you might have to get a newer graphics card.

Sorry.
