### ISSUE TITLE
Question: FasterParticle z-test

### ISSUE THREAD

**Issue by Skinnytorus** [framefield/tooll#4]
Am I correct saying that z-test is on by default for Faster particles (my screenshot attached)? This video seems to show that earlier the z-test was off by default: https://youtu.be/b1P4erXHATA?t=316
Or is it just me and my system? ;))
![particles-z](https://cloud.githubusercontent.com/assets/1675391/14122410/5b334572-f604-11e5-8d44-218fb6dd3436.jpg)

**Comment by pixtur** [comment]
Hi @Skinnytorus,

Z-Testing is always on by default. You can override this with the [Disable Z-Test] or [DepthStencilState] operators. Sadly, [FasterParticles] doesn't support its own sorting yet. For semi-transparent textures you will need to [Disable Z-Test] but also will have to live with artifacts. Eventually, [FasterParticles] need to support some form of sorting of particles by distance within the compute-shader. E.g. with a bucket-search.  Also  check [FasterParticleExamples]
