### ISSUE TITLE
Allow access to play speed from operators

### ISSUE THREAD

**Issue by thenfour** [framefield/tooll#45]
I would like to access play rate, and changes to play rate, from operators.

The reasoning for this is I would like to create some operators that play audio. It's important to access play speed from an audio playback operator so I can know when to accurately stop / play the audio.

**Comment by thenfour** [comment]
closing because i found a workaround

**Comment by pixtur** [comment]
You might be interested in looking into the new version of tooll3: 
https://github.com/still-scene/t3
