### ISSUE TITLE
forum / commercial usage

### ISSUE THREAD

**Issue by coderofsalvation** [framefield/tooll#49]
Hi, first of all thanks for creating this tool it looks amazing.
I'm somewhat confused by the MIT license in combination with 'free for non-commercial' on the website.
Is this like "dont sell this tool under a different name" to combat rebranding attempts?

Theoretically, anybody can sell a video exported by tooll, or selling an experience by connecting a PC running tooll to a beamer.
That would probably be good (in)directly for tooll no?
Are there premium (paid) services for commercial tooll users ? (feature-voting e.g.)

**Comment by pixtur** [comment]
Hi. I think the statement on the website is somewhat outdated. The current license is MIT and comes with all the rights granted with it, including using it for commercial projects.
