### ISSUE TITLE
"CONTRIBUTING" dead/wrong link for coding conventions/branches

### ISSUE THREAD

**Issue by necaremus** [framefield/tooll#5]
the `Contributing to Ruby on Rails`-link, https://github.com/framefield/tooll/wiki/Contribute, links to an empty wiki site. no idea how i have to style my code :3

**Comment by pixtur** [comment]
Good point: here you go: 
- https://github.com/framefield/tooll/wiki/Contribute
- https://github.com/framefield/tooll/wiki/Conventions

The rest of the wiki/documentation will be improved of the next couple of days.
