### ISSUE TITLE
[bug] CountInt Counter

### ISSUE THREAD

**Issue by lublak** [framefield/tooll#53]
Currently in a non-running state the reset at CountInt is at 0 and Counter at 1.
The default value here is always 0.
In addition, CounInt does not display a graph in the node like the Counter.

![grafik](https://user-images.githubusercontent.com/44057030/178144528-410d6582-67c8-4b20-b9ab-bf9bd5b69c3f.png)

**Comment by pixtur** [comment]
Wrong repo
