### ISSUE TITLE
[feature request] drag output to another output

### ISSUE THREAD

**Issue by lublak** [framefield/tooll#54]
![grafik](https://user-images.githubusercontent.com/44057030/178144627-769fe0cc-9d40-445b-acdd-fe070f7597a3.png)
Sometimes you want to combine certain outputs. Especially when working with boolean values.
It would be handy if you connect the output of one node with the output of another node to get a list that supports exactly these two outputs and also connects them automatically. Here it would be e.g. an and or an or.

**Comment by pixtur** [comment]
I implemented this partially: You first have to select the operators and then drag the output of one. 
But it needs a ton of tweaking.

Wrong repo.
