### ISSUE TITLE
UI-Ehancement and issues with contributing/understanding of workflow

### ISSUE THREAD

**Issue by necaremus** [framefield/tooll#6]
Huhu,
i have a problem with understanding the workflow. It is not clear, where or how i should upload my changes. I've created a Fork where i uploaded the [clean_up version of FullTextSelection OnTrippleClick](https://github.com/necaremus/tooll/blob/clean_up/Tooll/Components/TextButtonEdit.xaml.cs).
I do feel uncomfortable pushing changes to master, because i think, that the final decision should be on your end, but i couldn't find a Wiki or Doc entry stating how/where i should upload self-initiated changes. I've read [here](https://github.com/framefield/tooll/wiki/Contribute#if-you-want-to-improve-the-ui) that i should start an Issue before doing such things - this is it :]

Other things i would love to see:
- an accessible To-Do list
  - `There are many potential enhancements and inconsistencies, we would love to get help with.`
    _I'm trying to get back into coding. Stuff that is too trivial/boring for you could be just the right thing for me ;)_
- working Wiki-links  
  - [UI enhancements](https://github.com/framefield/tooll/wiki/UI-enhancements)
  - [Operators that would be nice to have](https://github.com/framefield/tooll/wiki/Operators-that-would-be-nice-to-have) 
    _Maybe i could even help with creating some Operators._

_Note: it's the first time i am actually working with GitHub. If i ask something that seems obvious to you, i'm sorry. (Like: How to manage branches/forks and pushes?)_

so far, 
neeca

**Comment by pixtur** [comment]
Hi neeca,

thanks for your contribution. I believe the workflow would be a pull request. Since your forked the project, pushing to develop should be just fine. Don’t be afraid, you can’t break anything because you don’t have direct write permissions to the repository.

If things work out, as they should we should get a notification about your pull-request and I can review and add your changes.

I’m super excited, btw! This is the first contribution ever!

**Comment by necaremus** [comment]
[created a Pull-Request on github.com](https://github.com/framefield/tooll/pull/7)
i think i got it right now. I messed around and up before... 
didn't find the option to revert a commit, that is why there are 3 commits but only 1 changed file :D 
on top of that: i think i messed up your code-structure with the github desktop application, i'm sorry :'(

**Comment by pixtur** [comment]
Hi again, 

I'm still in the middle of writing the Wiki-Pages. The two you asked for, I just finished :-)
