### ISSUE TITLE
framefield/tooll/tree/develop

### ISSUE THREAD

**Issue by necaremus** [framefield/tooll#9]
so... i thought i should try to get the develop branch working, if i gonna fork into it anyway.
stupid me thought, would be good idea to start with broken ssh-key, so i can directly start with my "next problem" -> nah... had to fix several stuff first, until i got to this exception: 
![tooll_develop](https://cloud.githubusercontent.com/assets/17855840/14161988/3e3a4d14-f6e8-11e5-85f1-16d3ff6538ca.jpg)

> this exception is thrown with working ssh-key, master branch still working perfectly 

guess i will not be able to fix dat :3
if i assume correct: it trys to access something on github i have no access to ;p

gonna try to wrap a logger around this exception, because the Log-files are still all empty ;D ~~
i can still work with the master-branch ^-^

**Comment by drcynic** [comment]
Ah I see, in Config/ProjectSettings.json you can change the entry "Git.OperatorRepositoryURL" to the url for the public operators, then it will work again (see this commit https://github.com/framefield/tooll/commit/5b157a54edf87d1658d81bb69e0f7abe1486c7d7 which changed this entry to the private one when creating the develop branch).
Perhaps we should split develop into develop_public and develop_private to separate these things...

**Comment by pixtur** [comment]
Good idea. And introduce topic or feature-branches again.

**Comment by necaremus** [comment]
morning ... i was a bit drunk when i posted that... no idea why i added a whole screen and not just the exception x_X
however: i got a working develop repo now... 

```
"Git.OperatorRepositoryURL": "git@github.com:framefield/tooll_operators.git",
"Git.OperatorRepositoryBranch": "develop",
```

-> throws an Auth.Fail Exception

```
"Git.OperatorRepositoryURL": "git@github.com:framefield/tooll_operators.git",
"Git.OperatorRepositoryBranch": "master",
```

-> works

now i want to build a "clean" public version for forks:

> [generateBuildProperties.vbs](https://github.com/framefield/tooll/blob/master/Helper/generateBuildProperties.vbs)

```
if WScript.Arguments.Count > 1 then
    buildNr = WScript.Arguments(1)
    branchName = WScript.Arguments(2)
    revisionHash = WScript.Arguments(3)
else
    'create local buildproperties.cs file only if it not exists
    if (fso.FileExists(filename)) then WScript.Quit 0
    WScript.Echo "Local build"
end if
```

it jumps into the `if WScript.Arguments.Count > 1 then` and throws an `out of range` exception - afterwards i get lots of errors, because the "BuildProperties.cs" is missing. 

---

`if WScript.Arguments.Count >= 4 then`
-> works

pull request incoming :D
